### ISSUE TITLE
There exists a bug in persist.h

### ISSUE THREAD

**Issue by shiniaas** [DICL/CCEH#1]
In function clflush
volatile char *ptr = (char*)((unsigned long)data & (\~kCacheLineSize-1));
should be
volatile char *ptr = (char*)((unsigned long)data & (\~(kCacheLineSize-1)));
because ~ has a much higher priority

**Comment by moohnam** [comment]
Thank you for reporting. We fixed the bug. Our CCEH performs slightly better than before. 

Thank you again.
