### ISSUE TITLE
a question about load factor

### ISSUE THREAD

**Issue by erician** [DICL/CCEH#2]
When I tested insert operation with random keys, I can not get the load factor as you showed in the paper with linear probing distance of 4. So what may be wrong with my test? Thanks a lot.

**Comment by moohnam** [comment]
Hi @erician,

Can you be more specific? 
  - How much load factor did you get?
  - How large was the key size?

**Comment by erician** [comment]
The maximum load factor I got using your code is about 43% with the linear probing distance of 4, and the key and the value size are both 8-byte. Besides, the average load factors I tested for the different linear probing distance is 20% smaller than yours, with 160 million random keys.

**Comment by moohnam** [comment]
```
#include <iostream>

#include "util/pair.h"
#include "util/timer.h"
#include "util/fileio.h"

#include "src/CCEH.h"

using namespace std;

void clear_cache() {
#ifndef DEBUG
  const size_t size = 1024*1024*512;
  int* dummy = new int[size];
  for (int i=100; i<size; i++) {
    dummy[i] = i;
  }

  for (int i=100;i<size-(1024*1024);i++) {
    dummy[i] = dummy[i-rand()%100] + dummy[i+rand()%100];
  }

  delete[] dummy;
#endif
}

size_t clflushCount = 0;
size_t kWriteLatencyInNS = 0;
size_t splitCount = 0;

int main(void) {
  const size_t kInitialTableSize = 64 * 1024;
  const size_t kInsertSize = 160*1024*1024;
  const size_t kDataSize = kInsertSize;

  Timer t;

  Key_t* keys = new Key_t[kDataSize];

  for (size_t i = 0; i < kDataSize; ++i) {
    keys[i] = i+1;
  }

  Hash* table = new CCEH(kInitialTableSize/Segment::kNumSlot);

  clear_cache();
  t.Start();
  for (int i = 0; i < kInsertSize; ++i) {
    table->Insert(keys[i], reinterpret_cast<Value_t>(&keys[i]));
    if (i % 10000 == 0) cout << table->Utilization() << endl;
  }
  cout << table->Utilization() << endl;
  t.Stop();

  return 0;
}
```

This is a part of our test code. Can you tell the difference with your test code? I got the same result as the paper with this code.

**Comment by erician** [comment]
My test code is similar to yours. The following is your code about calculating the table's load factor, and it is not right when compiling with -DINPLACE. Is it the reason that we got different results about load factor?

double CCEH::Utilization(void) {
  size_t sum = 0;
  std::unordered_map<Segment*, bool> set;
  for (size_t i = 0; i < dir.capacity; ++i) {
    set[dir._[i]] = true;
  }
  for (auto& elem: set) {
    for (unsigned i = 0; i < Segment::kNumSlot; ++i) {
      if (elem.first->_[i].key != INVALID) sum++;
    }
  }
  return ((double)sum)/((double)set.size()*Segment::kNumSlot)*100.0;
}

**Comment by moohnam** [comment]
Yes, I think that might be the problem. Thank you. I will fix the code.

**Comment by moohnam** [comment]
I've just fixed the code, and got the same result. It was slightly more than 10% loss for the load factor. We will update the graph. Thank you again.
